# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rack-environmental 1.3.2 ruby lib

Gem::Specification.new do |s|
  s.name = "rack-environmental"
  s.version = "1.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Wyatt Greene"]
  s.date = "2015-11-22"
  s.description = "\n      Rack::Environmental indicates which environment your web application is running\n      in (staging, test, etc.).\n    "
  s.email = "techiferous@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/rack-environmental.rb",
    "test/rackapp/app.rb",
    "test/rackapp/config.ru",
    "test/railsapp/README",
    "test/railsapp/Rakefile",
    "test/railsapp/app/controllers/application_controller.rb",
    "test/railsapp/app/controllers/tommy_boy_controller.rb",
    "test/railsapp/app/helpers/application_helper.rb",
    "test/railsapp/app/helpers/tommy_boy_helper.rb",
    "test/railsapp/app/views/layouts/application.html.erb",
    "test/railsapp/app/views/tommy_boy/index.html.erb",
    "test/railsapp/app/views/tommy_boy/more.html.erb",
    "test/railsapp/config/boot.rb",
    "test/railsapp/config/database.yml",
    "test/railsapp/config/environment.rb",
    "test/railsapp/config/environments/development.rb",
    "test/railsapp/config/environments/production.rb",
    "test/railsapp/config/environments/test.rb",
    "test/railsapp/config/initializers/backtrace_silencers.rb",
    "test/railsapp/config/initializers/inflections.rb",
    "test/railsapp/config/initializers/mime_types.rb",
    "test/railsapp/config/initializers/new_rails_defaults.rb",
    "test/railsapp/config/initializers/session_store.rb",
    "test/railsapp/config/locales/en.yml",
    "test/railsapp/config/routes.rb",
    "test/railsapp/db/development.sqlite3",
    "test/railsapp/db/seeds.rb",
    "test/railsapp/doc/README_FOR_APP",
    "test/railsapp/log/development.log",
    "test/railsapp/log/production.log",
    "test/railsapp/log/server.log",
    "test/railsapp/log/test.log",
    "test/railsapp/public/404.html",
    "test/railsapp/public/422.html",
    "test/railsapp/public/500.html",
    "test/railsapp/public/favicon.ico",
    "test/railsapp/public/images/rails.png",
    "test/railsapp/public/javascripts/application.js",
    "test/railsapp/public/javascripts/controls.js",
    "test/railsapp/public/javascripts/dragdrop.js",
    "test/railsapp/public/javascripts/effects.js",
    "test/railsapp/public/javascripts/prototype.js",
    "test/railsapp/public/robots.txt",
    "test/railsapp/script/about",
    "test/railsapp/script/console",
    "test/railsapp/script/dbconsole",
    "test/railsapp/script/destroy",
    "test/railsapp/script/generate",
    "test/railsapp/script/performance/benchmarker",
    "test/railsapp/script/performance/profiler",
    "test/railsapp/script/plugin",
    "test/railsapp/script/runner",
    "test/railsapp/script/server",
    "test/railsapp/test/functional/tommy_boy_controller_test.rb",
    "test/railsapp/test/performance/browsing_test.rb",
    "test/railsapp/test/test_helper.rb",
    "test/railsapp/test/unit/helpers/tommy_boy_helper_test.rb",
    "test/sinatraapp/app.rb"
  ]
  s.homepage = "http://github.com/techiferous/rack-environmental"
  s.requirements = ["none"]
  s.rubygems_version = "2.2.2"
  s.summary = "Rack middleware that adds an indicator of your application environment"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack-plastic>, [">= 0.1.1"])
    else
      s.add_dependency(%q<rack-plastic>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<rack-plastic>, [">= 0.1.1"])
  end
end

